name: CI Process
run-name: ${{ github.actor }} is learning github actions
on: [push]

jobs:
  behave-testing:
    # Setup of simple OS of choice, i.e., Linux
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v4.2.2

      # Install Python and dependencies
      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'

      # Install Behave and dependencies
      - name: Install Behave and dependencies
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate
          pip install --upgrade pip
          pip install behave

      # Run Behave tests
      - name: Run Behave tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          behave features/Steps  # Point Behave to the correct folder with the capital S
