name: CI Process
run-name: ${{ github.actor }} is learning github actions
on: [push]

jobs:
  behave-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # List files to verify the folder structure
      - name: List files and directories
        run: |
          ls -R  # List all files and directories for verification

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'

      - name: Install Behave and dependencies
        run: |
          python -m venv venv  # Create virtual environment
          source venv/bin/activate  # Activate the virtual environment
          pip install --upgrade pip
          pip install behave

      - name: Verify virtual environment activation
        run: |
          source venv/bin/activate
          which python  # Confirm Python location
          python --version  # Confirm Python version
          pip freeze  # Confirm installed packages

      - name: Run Behave tests
        run: |
          source venv/bin/activate  # Activate the virtual environment
          ls features  # Check if the 'Steps' folder is visible
          behave features/Steps  # Run tests with the correct path
